export const get_scanCountRecordList_success = 'get_scanCountRecordList_success'
export const get_scanCountRecordList_failed = 'get_scanCountRecordList_failed'
export const get_scanCountRecordList_error = 'get_scanCountRecordList_error'
export const get_scanCountRecordList_waiting = 'get_scanCountRecordList_waiting'


export const get_scanCountRecordListMore_success = 'get_scanCountRecordListMore_success'
export const get_scanCountRecordListMore_failed = 'get_scanCountRecordListMore_failed'
export const get_scanCountRecordListMore_error = 'get_scanCountRecordListMore_error'
export const get_scanCountRecordListMore_waiting = 'get_scanCountRecordListMore_waiting'