export const get_peccancyListForHome_success = 'get_peccancyListForHome_success'
export const get_peccancyListForHome_failed = 'get_peccancyListForHome_failed'
export const get_peccancyListForHome_error = 'get_peccancyListForHome_error'
export const get_peccancyListForHome_waiting = 'get_peccancyListForHome_waiting'

export const get_peccancyListForHomeMore_success = 'get_peccancyListForHomeMore_success'
export const get_peccancyListForHomeMore_failed = 'get_peccancyListForHomeMore_failed'
export const get_peccancyListForHomeMore_error = 'get_peccancyListForHomeMore_error'
export const get_peccancyListForHomeMore_waiting = 'get_peccancyListForHomeMore_waiting'